name: build
on: push
jobs:
  matrix-builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"

  isaac-ros-tutorials:
    needs: matrix-builder
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-builder.outputs.matrix)}}
    steps:
    - run: build