name: build
on: push
jobs:
  matrix-builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0
    - name: Extract matrix
      id: set-matrix
      run: |
        bash scripts/ci_builder.sh
        echo "::set-output name=matrix::$(cat matrix.json)"
        #echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"

  isaac-ros-tutorials:
    needs: matrix-builder
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-builder.outputs.matrix)}}
    steps:
    - run: echo "run "