name: build

on: [push, workflow_dispatch]

jobs:
  matrix-builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0
    - name: Extract matrix
      id: set-matrix
      run: |
        TERM=xterm bash .github/ci_builder.sh
        echo "::set-output name=matrix::$(cat matrix.json)"

  isaac-ros-tutorial:
    needs: matrix-builder
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-builder.outputs.matrix)}} #variable: project
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0
    - name: "Build ${{ matrix.project }}"
      run: echo "run ${{ matrix.project }}"